# Fills the reading page's contents rail from the rendered article.
#
# The headings only exist after Markdown has run, so the table of contents is
# built from the real output rather than parsed out of source markdown — which
# would miss anything generated by a component and would disagree with the
# anchor IDs the reader actually lands on.
#
# Unlike the heading-anchor inspector this runs in every environment: contents
# are structure, not decoration, and a reading page missing them in dev is a
# reading page nobody proofread.
class Builders::Inspectors::Toc < SiteBuilder
  LEVELS = ".prose h2[id], .prose h3[id]"

  def build
    inspect_html do |document|
      nav = document.query_selector("[data-toc]")
      next unless nav

      headings = document.query_selector_all(LEVELS)
      # A contents list of one entry is a heading with extra steps.
      next if headings.size < 2

      # `hidden` sits on the <details> wrapper so an empty rail leaves no
      # stray summary behind; the nav itself is never separately hidden.
      wrap = document.query_selector("[data-toc-wrap]")
      wrap&.remove_attribute("hidden")
      nav.add_child(<<~HTML)
        <ol class="m-0 p-0 list-none flex flex-col gap-2">
          #{headings.map { |h| item(h) }.join}
        </ol>
      HTML
    end
  end

  private

  def item(heading)
    indent = (heading.name.downcase == "h3") ? " pl-3" : ""
    <<~HTML
      <li class="m-0#{indent}">
        <a
          href="##{heading["id"]}"
          class="block text-note leading-snug text-slate-11 hover:text-ruby-11 transition-colors aria-[current=true]:text-ruby-11"
        >#{text_of(heading)}</a>
      </li>
    HTML
  end

  # The heading anchor inspector appends a "#" link to each heading, so the
  # raw text would carry it into the contents list.
  def text_of(heading)
    heading.text.to_s.sub(/#\s*\z/, "").strip
  end
end
