require "minitest_helper"

# Cloudflare _redirects is generated by plugins/builders/redirects.rb at
# :site, :post_write. Tests read the resulting file from the destination.
REDIRECTS_PATH = File.join(__dir__, "..", "output", "_redirects")

class TestRedirects < Bridgetown::Test
  REDIRECTS = File.read(REDIRECTS_PATH) if File.exist?(REDIRECTS_PATH)

  def redirect_rules
    REDIRECTS.to_s.lines.filter_map do |line|
      next if line.strip.empty? || line.start_with?("#")

      source, target, status = line.split(/\s+/, 3)
      [source, target, status&.strip]
    end
  end

  def resolve_redirect(path)
    redirect_rules.each do |source, target, status|
      return [target, status] if source == path

      next unless source.end_with?("*")

      prefix = source.delete_suffix("*")
      next unless path.start_with?(prefix)

      splat = path.delete_prefix(prefix)
      return [target.gsub(":splat", splat), status]
    end

    nil
  end

  def blog_post_slugs
    Dir[File.join(__dir__, "..", "src", "_posts", "blog", "*.md")].map { |file|
      File.basename(file, ".md")
    }.sort
  end

  it "is generated" do
    refute_nil REDIRECTS, "Expected output/_redirects to exist after build"
  end

  it "redirects deleted pages to sensible new homes" do
    expect(REDIRECTS).must_match %r{^/cfps/\s+/speaking/\s+301$}
    expect(REDIRECTS).must_match %r{^/newsletter/\s+/posts/\s+301$}
    expect(REDIRECTS).must_match %r{^/podcasts/\s+/speaking/\s+301$}
    expect(REDIRECTS).must_match %r{^/snippets/\s+/posts/\s+301$}
  end

  it "wildcards /blog/* and /snippets/* into /p/:splat" do
    expect(REDIRECTS).must_match %r{^/blog/\*\s+/p/:splat\s+301$}
    expect(REDIRECTS).must_match %r{^/snippets/\*\s+/p/:splat\s+301$}
  end

  it "enumerates root-level post slugs into /p/:slug/" do
    expect(REDIRECTS).must_match %r{^/twitter-avatar/\s+/p/twitter-avatar/\s+301$}
  end

  it "does not include a /* catch-all (would loop on /)" do
    expect(REDIRECTS).wont_match(/^\/\*\s/)
  end

  it "permanently redirects every legacy /blog/* post URL without chains" do
    failures = []

    blog_post_slugs.each do |slug|
      source = "/blog/#{slug}/"
      result = resolve_redirect(source)
      unless result
        failures << "#{source}: missing redirect"
        next
      end

      target, status = result
      failures << "#{source}: expected 301 or 308, got #{status}" unless %w[301 308].include?(status)
      failures << "#{source}: expected /p/#{slug}/, got #{target}" unless target == "/p/#{slug}/"
      failures << "#{source}: target should not include a query string" if target.include?("?")
      failures << "#{source}: redirect chain through #{target}" if resolve_redirect(target)
    end

    expect(failures).must_equal []
  end

  it "points legacy blog destinations at self-canonical pages" do
    failures = []

    blog_post_slugs.each do |slug|
      destination = "/p/#{slug}/"
      html get destination

      unless last_response.status == 200
        failures << "#{destination}: returned #{last_response.status}"
        next
      end

      canonical = document.query_selector("link[rel='canonical']")&.[]("href")
      failures << "#{destination}: canonical mismatch" unless canonical == "https://andrewm.codes#{destination}"
    end

    expect(failures).must_equal []
  end
end
