require "minitest_helper"

# Cloudflare _redirects is generated by plugins/builders/redirects.rb at
# :site, :post_write. Tests read the resulting file from the destination.

class TestRedirects < Bridgetown::Test
  REDIRECTS = File.read(File.join(__dir__, "..", "output", "_redirects")) if File.exist?(File.join(__dir__, "..", "output", "_redirects"))

  it "is generated" do
    refute_nil REDIRECTS, "Expected output/_redirects to exist after build"
  end

  it "redirects deleted pages to sensible new homes" do
    expect(REDIRECTS).must_match %r{^/cfps/\s+/speaking/\s+301$}
    expect(REDIRECTS).must_match %r{^/newsletter/\s+/posts/\s+301$}
    expect(REDIRECTS).must_match %r{^/podcasts/\s+/speaking/\s+301$}
    expect(REDIRECTS).must_match %r{^/snippets/\s+/posts/\s+301$}
  end

  it "wildcards /blog/* and /snippets/* into /p/:splat" do
    expect(REDIRECTS).must_match %r{^/blog/\*\s+/p/:splat\s+301$}
    expect(REDIRECTS).must_match %r{^/snippets/\*\s+/p/:splat\s+301$}
  end

  it "enumerates root-level post slugs into /p/:slug/" do
    expect(REDIRECTS).must_match %r{^/twitter-avatar/\s+/p/twitter-avatar/\s+301$}
  end

  it "does not include a /* catch-all (would loop on /)" do
    expect(REDIRECTS).wont_match(/^\/\*\s/)
  end
end
