fix: true
parallel: true
format: progress

ignore:
  - ".bridgetown-build/**/*"
  - "node_modules/**/*"
  - ".github/**/*"
  - ".obsidian/**/*"
  - ".vscode/**/*"
  - "src/**/*":
      - Layout/LeadingCommentSpace
