# https://www.bridgetownrb.com/docs/resources

url: "https://andrewm.codes"
timezone: America/Phoenix
destination: "output"
template_engine: erb
permalink: simple
content_engine: resource

collections:
  newsletter:
    output: true
    permalink: "/:slug/"
  pages:
    permalink: "/:slug/"
  posts:
    permalink: "/:slug/"
    sort_by: date
    sort_direction: descending
  podcasts:
    output: false
    relations:
      has_many: podcast_episodes
  podcast_episodes:
    output: false
    sort_by: published_on
    sort_direction: descending
    relations:
      belongs_to: podcast
  cfps:
    output: true
    permalink: pretty

taxonomies:
  series:
    key: series
    title: "Series"

development:
  url: http://localhost:8080

cloudinary:
  cloud_name: andrewmcodes

pagination:
  enabled: true

plausible:
  domain: andrewm.codes
