# https://www.bridgetownrb.com/docs/resources

url: "https://andrewm.codes"
timezone: America/Phoenix
destination: "build"
template_engine: erb
permalink: simple
content_engine: resource

collections:
  pages:
    permalink: "/:slug/"
  posts:
    permalink: "/:slug/"
    sort_by: date
    sort_direction: descending
  podcasts:
    output: false
    relations:
      has_many: podcast_episodes
  podcast_episodes:
    output: false
    sort_by: published_on
    sort_direction: descending
    relations:
      belongs_to: podcast
  cfps:
    output: true
    permalink: pretty
  snippets:
    output: true
    permalink: "/snippets/:slug/"
    sort_by: date
    sort_direction: descending

taxonomies:
  series:
    key: series
    title: "Series"

development:
  url: http://localhost:8080

cloudinary:
  cloud_name: andrewmcodes

pagination:
  enabled: true

plausible:
  domain: andrewm.codes
