# Most settings are now in `config/initializers.rb`!
# A list of all available configuration options can be found here:
# https://www.bridgetownrb.com/docs/configuration/options
#

# url: "" # the base hostname & protocol for your site, e.g. https://example.com
# permalink: pretty
# template_engine: erb
# base_path: "/"
# timezone: America/Los_Angeles
# pagination:
#   enabled: true
permalink: "/:path.*/"

collections:
  projects:
    permalink: /:collection/:path.*
    output: true
  newsletter:
    permalink: /:collection/:path.*
    output: true

pagination:
  enabled: true

# feed:
#   categories:
#     - news
#     - updates

production:
  exclude:
    - "stories"
    - "assets/icons"
  url: "https://andrewm.codes"
