default_provider = "keychain"

[providers.keychain]
type = "keychain"
service = "fnox-andrewmcodes-v8"

[secrets]
CLOUDFLARE_API_KEY= { provider = "keychain", value = "CLOUDFLARE_API_KEY" }
CLOUDFLARE_EMAIL= { provider = "keychain", value = "CLOUDFLARE_EMAIL" }
BUZZSPROUT_API_TOKEN= { provider = "keychain", value = "BUZZSPROUT_API_TOKEN" }
WEBMENTION_IO_TOKEN= { provider = "keychain", value = "WEBMENTION_IO_TOKEN" }
