# Writes a Cloudflare-format `_redirects` file into the build output: static
# legacy/v7 redirects plus an enumerated per-post `/:slug/ → /p/:slug/` rule for
# every post. Consumed by Workers Static Assets. Intentionally has no `/*`
# catch-all (see the note in #build).
class Builders::Redirects < SiteBuilder
  # Static redirect rules, prepended verbatim to the generated `_redirects`.
  STATIC = <<~REDIRECTS
    # Cloudflare Pages _redirects — generated by Builders::Redirects.

    # ---- Deleted pages (from v7) ----
    /cfps/            /speaking/   301
    /follow/          /about/   301
    /sitemap/         /sitemap.xml   301
    /site/            /about/   301
    /site/*           /about/   301
    /newsletter/      /posts/   301
    /podcasts/        /speaking/   301
    /reading-list/    /about/   301
    /snippets/        /posts/   301
    /tags/            /posts/   301
    /tags/*           /posts/   301
    /category/        /posts/   301
    /category/*       /posts/   301
    /now/             /about/   301
    /timeline/        /posts/   301

    # ---- Updated targets ----
    /privacy/         /about/   301
    /analytics/       /about/   301
    /contact/         /about/   301

    # ---- External shortlinks ----
    /bluesky/         https://bsky.app/profile/andrewm.codes   302
    /github/          https://github.com/andrewmcodes   302
    /source/          https://github.com/andrewmcodes/andrewm.codes   302
    /r/setapp/        https://go.setapp.com/invite/3sztpuuq   302
    /resume/          /resume.pdf   302
    /ama/             https://github.com/andrewmcodes/andrewm.codes/discussions/categories/ama   302

    # ---- Post URL migration to /p/:slug/ ----
    /blog/*           /p/:splat   301
    /snippets/*       /p/:splat   301
  REDIRECTS

  # Registers the post_write hook that writes `_redirects` into the destination.
  # @return [void]
  def build
    hook :site, :post_write do |site|
      next unless site.config.destination

      post_lines = site.collections.posts.resources.map { |r|
        slug = File.basename(r.relative_path, ".*")
        "/#{slug}/    /p/#{slug}/   301"
      }

      contents = [
        STATIC,
        "",
        "# Root-level post slugs (enumerated to avoid colliding with nav pages)",
        *post_lines,
        ""
      ].join("\n")
      # No catch-all here: wrangler.jsonc's `not_found_handling: "404-page"`
      # serves /404.html on misses. A `/*` rule would match /, causing a loop.

      File.write(File.join(site.config.destination, "_redirects"), contents)
    end
  end
end
