name: ci

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["!main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/cache@v2.1.7
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Dependencies
        run: bundle install && yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
        env:
          STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}
